# Generated by Django 4.2 on 2023-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_handbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Est_category',
            new_name='EstCategory',
        ),
    ]
